### ISSUE TITLE
Improve CLI commands to take packages into account

### ISSUE THREAD

**Issue by zamotany** [TrueCar/gluestick#698]
Right now when installing gluestick in project gluestick-shared is downloaded from npm. This is undesired behavior, in development we want both gluestick and gluestick-shared to be installed from local dev version and both to be watched.

Ideally there should be some option to tell which packages to watch and install by eg. some regex in command arg.

edit

- [x] new command PR #708 
- [x] reinstall-dev command PR #709 
- [x] watch command PR #711 
- [x] reset-hard [WIP]
- [x] moving gs-shared PR #740 
## New
```
gluestick new <projectName> --dev ./gluestick
```
`dev` should be prefixed with `..` and `packages` should be added at the end, then by default all packages should be installed, and proper paths set for them in `package.json`
If `--dev` flag is not specfied, it should only install gluestick with version taken from gluestick-cli's `package.json`.
## Reinstall-dev
```
gluestick reinstall-dev
```
In project `package.json` should find every dependency starting with `gluestick`, which have path set instead of version string.
## Watch
```
gluestick watch
```
In project `package.json` should find every dependency starting with `gluestick`, which have path set instead of version string and start watching those packages.
## Reset-hard
```
gluestick reset-hard
```
In project `package.json` should find every dependency starting with `gluestick`, which have path set instead of version string and remove those packages from `node_modules`, remove `build` folder, `npm cache clean` and call `reinstall-dev`.

**Comment by lukewalczak** [comment]
Issue was replaced with #720
